apiVersion: v1
kind: Service
metadata:
  name: hc-di-mq
  namespace: hc-di
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: ui
  - port: 4369
    protocol: TCP
    targetPort: 4369
    name: discovery
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: amqp
  selector:
    app-tpl: hc-di-mq

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app-dep: hc-di-mq
  name: hc-di-mq
  namespace: hc-di
spec:
  selector:
    matchLabels:
      app-tpl: hc-di-mq
  replicas: 1
  minReadySeconds: 10     
  serviceName: hc-di-mq
  template:
    metadata:
      labels:
        app-tpl: hc-di-mq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: rabbitmq:management
        name: hc-di-mq
        ports:
        - containerPort: 15672
          name: ui
        - containerPort: 4369
          name: discovery
        - containerPort: 5672
          name: amqp
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          value: "1WqgH8N2v1qDBCADbNy8Bg9IkTREYpu79m6q+0t36lQ="
        imagePullPolicy: Always   
        volumeMounts:
        - name: v-mq-disk
          mountPath: /var/lib/rabbitmq/mnesia/
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: v-mq-disk
          persistentVolumeClaim:
            claimName: pvc-mq-disk

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mq-disk
  namespace: hc-di
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-mq-disk
  storageClassName: managed-csi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mq-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/ac164670-6bc6-4f61-b7a7-2ecbeefa13e4/resourceGroups/MC_H-Connect-Kube_demoAksCluster_westeurope/providers/Microsoft.Compute/disks/demoMqAksDisk
    volumeAttributes:
      fsType: ext4

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hc-di-mq
  namespace: hc-di
spec:
  defaultBackend:
    service:
      name: hc-di-mq
      port:
        number: 15672