apiVersion: v1
kind: Service
metadata:
  name: hc-di-sql-pv
  namespace: hc-di
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tsql
  selector:
    app-tpl: hc-di-sql-pv

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hc-di-sql-pv
  namespace: hc-di
spec:
  replicas: 1
  selector:
     matchLabels:
       app-tpl: hc-di-sql-pv
  serviceName: hc-di-sql-pv
  template:
    metadata:
      labels:
        app-tpl: hc-di-sql-pv
    spec:
      terminationGracePeriodSeconds: 30
      hostname: hc-di-sql-demo
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: alessandronostini/deploy:hc-di-sql-demo-linux
        resources:
          requests:
            memory: "1G"
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_AGENT_ENABLED
          value: "True"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo PostStart handler; echo waiting 10 sec; sleep 10; /init/start.sh"]
        volumeMounts:
        - name: v-sql-disk
          mountPath: /var/opt/mssql

      nodeSelector:
        kubernetes.io/os: linux

  volumes:
    - name: v-sql-disk
      persistentVolumeClaim:
        claimName: pvc-sql-disk

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sql-di-sk
  namespace: hc-di
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-sql-disk
  storageClassName: managed-csi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sql-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/ac164670-6bc6-4f61-b7a7-2ecbeefa13e4/resourceGroups/MC_H-Connect-Kube_demoAksCluster_westeurope/providers/Microsoft.Compute/disks/demoSqlAksDisk
    volumeAttributes:
      fsType: ext4

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hc-di-sql-pv
  namespace: hc-di
spec:
  defaultBackend:
    service:
      name: hc-di-sql-pv
      port:
        number: 1433
